/gazebo_ros_control:   
    pid_gains:
      scooter_right_wheel_joint:
        p: 5.0
        i: 0.0 
        d: 0.00
        i_clamp: 0.0

      scooter_left_wheel_joint:
        p: 5.0
        i: 0.0 
        d: 0.00
        i_clamp: 0.0

      # caster_front_wheel_joint:
      #   p: 10.0
      #   i: 10.0 
      #   d: 0.0
      #   # i_clamp: 0.1

      # caster_back_wheel_joint:
      #   p: 10.0
      #   i: 10.0 
      #   d: 0.0
      #   # i_clamp: 0.1

        
